export const items =[
    {
        id: 1,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 2,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 3,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 4,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 5,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 6,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 7,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 8,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 9,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 10,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 11,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 12,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 13,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 14,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      {
        id: 15,
        tag1: "Non Degree",
        tag2: "Multiple Countries",
        tag3:'Fully Funded',
        pemberi:'Kemdikbud Indonesia',
        title: "IISMA : Indonesian International Student Mobility Awards",
        open:'24 Jan 2023',
        close: '25 Jan 2023',
        harga: "Rp 500.000",
        linkImg: "../../assets/Rectangle2.svg"
      },
      
]